apiVersion: apps/v1
kind: Deployment
metadata:
  name: preference
  labels:
    app: preference
    version: v1
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"      
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preference
      version: v1
  template:
    metadata:
      labels:
        app: preference
        version: v1
    spec:
      containers:
      - name: preference-container
        image: navkkrnair/istio-preference:1.0
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080   
            protocol: TCP
        securityContext:
          privileged: false
---

apiVersion: v1
kind: Service
metadata:
  name: preference
  labels:
    app: preference    
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: preference
    version: v1