apiVersion: apps/v1
kind: Deployment
metadata:
  name: preference
  labels:
    app: preference
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preference
      version: v1
  template:
    metadata:
      labels:
        app: preference
        version: v1
    spec:
      containers:
      - name: preference-container
        image: navkkrnair/istio-preference:1.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - ls
            - /var/ready
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 1
        ports:
          - name: http
            containerPort: 8080   
            protocol: TCP
          - name: jolokia
            containerPort: 8778
            protocol: TCP
          - name: prometheus
            containerPort: 9779
            protocol: TCP
        securityContext:
          privileged: false
---

apiVersion: v1
kind: Service
metadata:
  name: preference
  labels:
    app: preference    
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: preference
    version: v1